server:
   port: 80

spring:
  application:
     name: ebuy-zuul

# 日志配置
logging:
  level:
    com:
      yc:
        ebuy:
          dao: debug
          web: warn
#zuul网关
zuul:
   routes:
      ebuy-index:
         path: /**
         #过滤敏感头
         sensitiveHeaders: 
      ebuy-back:
         path: /back/**
         #过滤敏感头
         sensitiveHeaders: 
      ebuy-order:
         path: /order/**
         #过滤敏感头
         sensitiveHeaders: 
      


#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000