server:
   port: 80

spring:
  application: 
    name: ebuy-index
#连接数据库配置  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/c76-s3-phooy-ebuy
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  #实体类别名 com.yc.C76S3PlySpringBoot.bean -> bean
  type-aliases-package: com.yc.ebuy.bean
  #驼峰命名法 类成员别名
  configuration:
    map-underscore-to-camel-case: true

#测试类配置  
logging:
  level:
    com:
      yc:
        ebuy:
          dao: debug
          web: warn